### ISSUE TITLE
Debian high priority metabug

### ISSUE THREAD

**Issue by onlyjob** [lizardfs/lizardfs#361]
Official Debian package need to meet certain criteria for inclusion in order to replace v2.6.0 packages in "testing" suite with v3.9.4. Here are high priority blocking bugs that would be nice to fix ASAP:

- [ ] #354 FTBFS@kfreebsd
- [x] ~~#352 FTBFS@powerpc~~
- [x] ~~#363 FTBFS with CMake-3.4~~
- [x] ~~#349 chunkserver errors "EBADF (Bad file descriptor)"~~
- [x] ~~#356 loss of _xor2_ chunks~~

New release is not necessary as I can cherry-pick fixes on top of 3.9.4. Thanks.

**Comment by onlyjob** [comment]
I think post-3.9.4 fixes accumulated in "master" justify new release.

There are fixes for known data loss; fixes for two different FTBFS (hopefully fix for third FTBFS will be merged soon); Systemd notification feature and bug fixes for CGI and chunkserver replication.

Please consider releasing to accommodate critical fixes.

**Comment by onlyjob** [comment]
I'm closing this bug since LizardFS with all the fixes migrated to Debian "testing": https://packages.debian.org/source/stretch/lizardfs.

But seriously, please, pretty please release official 3.9.5 ASAP as it is bad that last version is affected by such problems.
